### ISSUE TITLE
Find better icon

### ISSUE THREAD

**Issue by matthiaskern** [matthiaskern/open-pip-menubar#3]

**Comment by pablopunk** [comment]
### Idea ([download .icns](https://cl.ly/2a1G0e3n0R24))

![open-pip-menubar](https://user-images.githubusercontent.com/4324982/27888666-44b4a9da-61b5-11e7-9211-983d8d00c018.png)

**Comment by matthiaskern** [comment]
Great! Thanks for the effort! Added in new version
